name: app_store_connect_api_v1
description: App Store Connect Api
version: 1.0.4
homepage: https://github.com/iptodays/app_store_connect_api

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/convert
  convert: ^3.1.1
  # https://pub.dev/packages/dart_jsonwebtoken
  dart_jsonwebtoken: ^2.14.0
  # https://pub.dev/packages/dio
  dio: ^5.6.0
  # https://pub.dev/packages/crypto
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter: